trigger:
- none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight mutation
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
- group: stryker-net-sample

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: pipeline-templates

extends:
  template: Tests\dotnet-mutation.yml@templates
