trigger:
  - master

schedules:
- cron: "0 */12 * * * "
  displayName: Build every 12 hours
  branches:
    include:
    - master

variables:
- group: stryker-net-sample

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: pipeline-templates

extends:
  template: templates\c_sharp\template.yml@templates
  