name: .NET Core - Build & Test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/README.md'
    - '**/*.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Stryker.Net.Sample     

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Build
      run: dotnet build
            
    - name: Install Coverlet
      run: dotnet tool install -g coverlet.console

    - name: Test
      run: coverlet bin/Debug/netcoreapp3.1/Stryker.Net.Sample.Tests.dll -t dotnet -a "test --no-build" -f opencover
      working-directory: Stryker.Net.Sample/Stryker.Net.Sample.Tests      
      
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v1.0.13

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=raschmitt
          -Dsonar.projectKey=raschmitt_stryker-net-sample
          -Dsonar.sonar.cs.opencover.reportsPaths=**/*.opencover.xml

